services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=padsign.trustlynx.com
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_PROXY_HEADERS=xforwarded
    command: start-dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data
  dmss-archive-services:
    container_name: dmss-archive-services
    restart: always
    ports:
      - '86:8090'
    volumes:
      - './dmss-archive-services:/confs'
    environment:
      - SPRING_CONFIG_LOCATION=/confs/
    image: 'trustlynx/dmss-archive-services:24.2.0.8'
  dmss-container-and-signature-services:
    container_name: dmss-container-and-signature-services
    restart: always
    ports:
      - '84:8092'
    volumes:
      - './dmss-container-and-signature-services:/confs'       
    environment:
      - SPRING_CONFIG_LOCATION=/confs/
    image: 'trustlynx/container-signature-service:24.3.0.29'
    extra_hosts:
      - "host.docker.internal:host-gateway"    
  dmss-archive-services-fallback:
    container_name: dmss-archive-services-fallback
    restart: always
    ports:
      - '93:8095'
    volumes:
      - './dmss-archive-services-fallback:/dmss-archive-services-fallback'
      - './docs:/docs'
    environment:
      - SPRING_CONFIG_LOCATION=/dmss-archive-services-fallback/application.yml
    image: 'trustlynx/dmss-archive-services-fallback:24.0.5'
  ps-server:
    image: 'mihailsgordijenko/ps-server:1.2'
    container_name: ps-server
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - nginx
    environment:
      - NO_PROXY=keycloak,ps-server,nginx,localhost,127.0.0.1
      - no_proxy=keycloak,ps-server,nginx,localhost,127.0.0.1
      - HTTP_PROXY=
      - http_proxy=
      - HTTPS_PROXY=
      - https_proxy=
    volumes:
      - ./config/config.js:/usr/src/app/config.js
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ps-client
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      default:
        aliases:
          - padsign.trustlynx.com

  ps-client:
    image: mihailsgordijenko/ps-client:5.0
    container_name: ps-client
    restart: unless-stopped
    # No host port mapping; accessed via nginx by service name
    volumes:
      # Override runtime configuration file inside the client image
      - ./config/constants.json:/usr/share/nginx/html/portal/constants.json:ro
      # Override nginx config to remove any internal redirects
      - ./client/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Override logo used by the SPA
      - ./config/TLlogo.png:/usr/share/nginx/html/portal/logo.png:ro
    networks:
      - default

networks:
  default:
    driver: bridge 

volumes:
  keycloak_data: 
